:concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - critical
  - default
  - low

:scheduler:
  :schedule:
    SyncFiberGraphInfosJob:
      cron: '0 */4 * * *'
      description: "Sync fiber graph nodes and channels"
    SyncCkbCloseTransactionsJob:
      every: "2h"
      description: "Sync closed transactions of fiber graph channels"
    StatisticsRefreshJob:
      cron: '0 * * * *'
      description: "Hourly refresh of fiber statistics"
