name: Deploy to testnet

on:
  push:
    branches:
      - testnet
jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
  deploy-update:
    needs: build
    strategy:
      matrix:
        workload: [fiber-explorer, fiber-explorer-sidekiq]
    uses: ./.github/workflows/update-image.yml
    with:
      k8s-namespace: fiber-explorer
      k8s-workload: ${{ matrix.workload }}
      image-name: ${{ needs.build.outputs.image-name }}
      image-tag: ${{ needs.build.outputs.image-tag }}
    secrets: inherit
